### ISSUE TITLE
Horizon / PHP Redis Extension

### ISSUE THREAD

**Issue by lonnylot** [tighten/laravelm1#7]
`pecl install redis` will not work until https://github.com/phpredis/phpredis/pull/1935 is tagged and released.

This prevents horizon from working (and presumably any requests to Redis)

**Comment by lonnylot** [comment]
Just to clarify what I meant: `pecl install redis` _will_ work. However, the redis extension will segfault when you try to use it.

**Comment by mattstauffer** [comment]
ahhh.. I know I tested that Redis was working but not that the extension was.
